### ISSUE TITLE
v2 firmware release

### ISSUE THREAD

**Issue by gadgetmies** [dronecz/ESP32-Reflow-Controller#6]
I've owned the board for a few years now, but it has had an issue with the PID that the temperature never rises to the peak temperature. I thought I'd try to adjust the parameters (increase Kp I suppose?) and flash the updated firmware on the board. I was able to build the firmware (Arduino IDE v2.3.2 & esp32 boards v3.0.7, master branch), but the application crashes some seconds after boot causing a reboot. I tried debugging the issue, but the behaviour was very strange (for loop in digitalButton running to i = 546) that I suspect the device either runs out of memory or there is something funky going on with the libraries / board support. As I uploaded the firmware to the board and thus replaced the original, I now have a bricked device. Thus I was wondering if you could perhaps share some firmware version you have built that has been tested and proven to work? I would of course appreciate if there would be a version with tweaked PID parameters, but would be grateful for any working version.

**Comment by dronecz** [comment]
Please try to downgrade ESP suppport to 1.0.6 version. I remember that anythink higher than this will cause issue which you described. I tried to find out why this is happening, but without luck. Pls let me know if your issue is solved.

**Comment by gadgetmies** [comment]
I tried this, but the SD library do not seem to be compatible with that version anymore:

```
Arduino/libraries/SD/src/utility/Sd2PinMap.h:527:2: error: #error Architecture or board not supported.
 #error Architecture or board not supported.
```

I tried using the 2.0.17 version of the ESP boards, but although it compiles, the device seems to freeze a few seconds after boot.

**Comment by dronecz** [comment]
Try to move this folder temporarily outside of the `library` folder, but sketch should be compiled with SD library from Espressif SDK. When I try to compile it, it does work. 

![Image](https://github.com/user-attachments/assets/179d3355-e53c-4f0c-8679-728c5f7822f3)

I will try to make compiled version and upload it here.

**Comment by gadgetmies** [comment]
Got the firmware to compile using the ESP32 support v1.0.6 by moving the SD library out of the way as well as patching the platform.txt files to use python3 instead of python (https://github.com/espressif/arduino-esp32/issues/4717#issuecomment-1070801525) and am happy to report that the controller seems to work now 🥳! I zipped and uploaded the build directory files to Google Drive: https://drive.google.com/file/d/1EPUK_uM__pfjzBjSILQh9j3xufqQTB2y/view.

Thank you for the help! I can now try to adjust the PID values to make the oven function properly. Hopefully some day support for newer ESP32 support versions will be available!

**Comment by gadgetmies** [comment]
Oh, closed the issue, but perhaps if you have time, it would be great if you would create a release here on Github for the v2 firmware in order to make that available for anyone else having issues.
